services:
  db:
    image: mysql:8.0
    container_name: task_manager_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "9523511173"
      MYSQL_DATABASE: "task_manager"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Updated Backend Service
  backend:
    build:
      context: .                  # Sets the context to the root directory
      dockerfile: ./backend/Dockerfile  # Points to the Dockerfile inside backend/
    container_name: task_manager_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:9523511173@db/task_manager
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task_manager_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  mysql_data: